### ISSUE TITLE
Current CMake test integration

### ISSUE THREAD

**Issue by hartwork** [hsluv/hsluv-c#3]
Hi!

I noticed that the current integration of tests with CMake needs users to learn about `./tests/test_hsluv` themselves, e.g. by looking at `.travis.yml` or `tests/CMakeLists.txt`, and then running that command. CMake has [`add_test`](https://cmake.org/cmake/help/v3.0/command/add_test.html) and [`enable_testing`](https://cmake.org/cmake/help/v3.0/command/enable_testing.html#command:enable_testing) that allow plain `make test` to the user. Is that something you decided against on purpose?

If `make test` is intended to not be supported, maybe the readme could have a sentence about how to run tests.

What do you think?

**Comment by mity** [comment]
It is not because it's intended. It's that way just because an initial state of any feature is "unimplemented" and I have never needed it.

**Comment by hartwork** [comment]
Should I make a pull request?

**Comment by mity** [comment]
Feel free to.
